
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ACTION AND ARROW CLOSELIST COLON COMMA DOT ENDLABELS ENDMODULE ENDOPTIONS EQUAL GUARD ID IMPORT INIT INT LABELS MODULE NOT OPENLIST OPTIONS PARAMS PREDICATE SEMICOLON ST\nprogram : import labels module options\n\nnil :\n\nimport : IMPORT path\n\npath : ID path\n     | DOT path\n     | nil\n\nlabels : LABELS labellist ENDLABELS\n\nmodule : MODULE automata ENDMODULE\n\noptions : OPTIONS ENDOPTIONS\n        | nil\n\nlabellist : label\n          | label COMMA labellist\n          | nil\n\nlabel : ID COLON OPENLIST act_or_pred_list CLOSELIST\n\nact_or_pred_list : act_or_pred\n                 | act_or_pred AND act_or_pred_list\n\nact_or_pred : ACTION COLON ID COMMA PARAMS COLON OPENLIST param_dec CLOSELIST\n            | PREDICATE COLON ID COMMA PARAMS COLON OPENLIST param_dec CLOSELIST\n            | PREDICATE COLON NOT ID COMMA PARAMS COLON OPENLIST param_dec CLOSELIST\n            | nil\n\nparam_dec : ID\n          | ID COMMA param_dec\n          | nil\n\nautomata : state_dec_wrapper cond_dec_wrapper trel\n         | state_dec_wrapper trel\n         | nil\n\ncond_dec_wrapper : GUARD COLON OPENLIST cond_dec CLOSELIST SEMICOLON\n\ncond_dec : INT COLON ID\n         | INT COLON INIT\n         | INT COLON ID COMMA cond_dec\n         | INT COLON INIT COMMA cond_dec\n         | nil\n\nstate_dec_wrapper : ST COLON OPENLIST state_dec CLOSELIST SEMICOLON\n\nstate_dec : INT COLON ID\n          | INT COLON INIT\n          | INT COLON ID COMMA state_dec\n          | INT COLON INIT COMMA state_dec\n          | nil\n\ntrel : event boolexp ARROW INT SEMICOLON trel\n     | nil\n\nevent : OPENLIST CLOSELIST\n      | OPENLIST ID CLOSELIST\n\nboolexp : INT AND GUARD EQUAL ID\n        | INT AND GUARD EQUAL INT\n        | INT\n'
    
_lr_action_items = {'IMPORT':([0,],[3,]),'$end':([1,10,18,20,28,29,],[0,-2,-1,-10,-9,-8,]),'LABELS':([2,3,6,7,8,9,16,17,],[5,-2,-3,-2,-2,-6,-4,-5,]),'ID':([3,5,7,8,26,33,60,61,68,72,74,76,103,104,110,111,],[7,15,7,7,15,42,70,71,78,82,84,88,106,106,106,106,]),'DOT':([3,7,8,],[8,8,8,]),'MODULE':([4,25,],[11,-7,]),'ENDLABELS':([5,12,13,14,26,37,58,],[-2,25,-11,-13,-2,-12,-14,]),'OPTIONS':([10,29,],[19,-8,]),'ST':([11,],[24,]),'ENDMODULE':([11,21,22,23,30,31,35,39,75,77,83,86,],[-2,29,-2,-26,-2,-25,-40,-24,-2,-33,-27,-39,]),'COMMA':([13,58,70,71,78,79,82,84,85,106,],[26,-14,80,81,89,90,93,94,95,111,]),'COLON':([15,24,32,48,49,56,63,91,92,100,],[27,36,40,60,61,68,74,98,99,105,]),'ENDOPTIONS':([19,],[28,]),'GUARD':([22,54,77,],[32,66,-33,]),'OPENLIST':([22,27,30,36,40,75,77,83,98,99,105,],[33,38,33,45,51,33,-33,-27,103,104,110,]),'CLOSELIST':([33,38,42,45,46,47,50,51,55,57,59,62,64,69,78,79,84,85,89,90,94,95,96,97,101,102,103,104,106,107,108,109,110,111,112,113,114,115,116,],[41,-2,52,-2,58,-15,-20,-2,67,-38,-2,73,-32,-16,-34,-35,-28,-29,-2,-2,-2,-2,-36,-37,-30,-31,-2,-2,-21,112,-23,113,-2,-2,-17,-18,116,-22,-19,]),'INT':([34,41,45,51,52,53,76,89,90,94,95,],[44,-41,56,63,-42,65,87,56,56,63,63,]),'ACTION':([38,59,],[48,48,]),'PREDICATE':([38,59,],[49,49,]),'AND':([38,44,47,50,59,112,113,116,],[-2,54,59,-20,-2,-17,-18,-19,]),'ARROW':([43,44,87,88,],[53,-45,-44,-43,]),'NOT':([61,],[72,]),'SEMICOLON':([65,67,73,],[75,77,83,]),'EQUAL':([66,],[76,]),'INIT':([68,74,],[79,85,]),'PARAMS':([80,81,93,],[91,92,100,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'import':([0,],[2,]),'labels':([2,],[4,]),'path':([3,7,8,],[6,16,17,]),'nil':([3,5,7,8,10,11,22,26,30,38,45,51,59,75,89,90,94,95,103,104,110,111,],[9,14,9,9,20,23,35,14,35,50,57,64,50,35,57,57,64,64,108,108,108,108,]),'module':([4,],[10,]),'labellist':([5,26,],[12,37,]),'label':([5,26,],[13,13,]),'options':([10,],[18,]),'automata':([11,],[21,]),'state_dec_wrapper':([11,],[22,]),'cond_dec_wrapper':([22,],[30,]),'trel':([22,30,75,],[31,39,86,]),'event':([22,30,75,],[34,34,34,]),'boolexp':([34,],[43,]),'act_or_pred_list':([38,59,],[46,69,]),'act_or_pred':([38,59,],[47,47,]),'state_dec':([45,89,90,],[55,96,97,]),'cond_dec':([51,94,95,],[62,101,102,]),'param_dec':([103,104,110,111,],[107,109,114,115,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> import labels module options','program',4,'p_program','lexer_and_parser.py',159),
  ('nil -> <empty>','nil',0,'p_nil','lexer_and_parser.py',166),
  ('import -> IMPORT path','import',2,'p_import','lexer_and_parser.py',173),
  ('path -> ID path','path',2,'p_path','lexer_and_parser.py',180),
  ('path -> DOT path','path',2,'p_path','lexer_and_parser.py',181),
  ('path -> nil','path',1,'p_path','lexer_and_parser.py',182),
  ('labels -> LABELS labellist ENDLABELS','labels',3,'p_labels','lexer_and_parser.py',190),
  ('module -> MODULE automata ENDMODULE','module',3,'p_module','lexer_and_parser.py',197),
  ('options -> OPTIONS ENDOPTIONS','options',2,'p_options','lexer_and_parser.py',204),
  ('options -> nil','options',1,'p_options','lexer_and_parser.py',205),
  ('labellist -> label','labellist',1,'p_labellist','lexer_and_parser.py',212),
  ('labellist -> label COMMA labellist','labellist',3,'p_labellist','lexer_and_parser.py',213),
  ('labellist -> nil','labellist',1,'p_labellist','lexer_and_parser.py',214),
  ('label -> ID COLON OPENLIST act_or_pred_list CLOSELIST','label',5,'p_label','lexer_and_parser.py',224),
  ('act_or_pred_list -> act_or_pred','act_or_pred_list',1,'p_act_or_pred_list','lexer_and_parser.py',231),
  ('act_or_pred_list -> act_or_pred AND act_or_pred_list','act_or_pred_list',3,'p_act_or_pred_list','lexer_and_parser.py',232),
  ('act_or_pred -> ACTION COLON ID COMMA PARAMS COLON OPENLIST param_dec CLOSELIST','act_or_pred',9,'p_act_or_pred','lexer_and_parser.py',242),
  ('act_or_pred -> PREDICATE COLON ID COMMA PARAMS COLON OPENLIST param_dec CLOSELIST','act_or_pred',9,'p_act_or_pred','lexer_and_parser.py',243),
  ('act_or_pred -> PREDICATE COLON NOT ID COMMA PARAMS COLON OPENLIST param_dec CLOSELIST','act_or_pred',10,'p_act_or_pred','lexer_and_parser.py',244),
  ('act_or_pred -> nil','act_or_pred',1,'p_act_or_pred','lexer_and_parser.py',245),
  ('param_dec -> ID','param_dec',1,'p_param_dec','lexer_and_parser.py',253),
  ('param_dec -> ID COMMA param_dec','param_dec',3,'p_param_dec','lexer_and_parser.py',254),
  ('param_dec -> nil','param_dec',1,'p_param_dec','lexer_and_parser.py',255),
  ('automata -> state_dec_wrapper cond_dec_wrapper trel','automata',3,'p_automata','lexer_and_parser.py',265),
  ('automata -> state_dec_wrapper trel','automata',2,'p_automata','lexer_and_parser.py',266),
  ('automata -> nil','automata',1,'p_automata','lexer_and_parser.py',267),
  ('cond_dec_wrapper -> GUARD COLON OPENLIST cond_dec CLOSELIST SEMICOLON','cond_dec_wrapper',6,'p_cond_dec_wrapper','lexer_and_parser.py',279),
  ('cond_dec -> INT COLON ID','cond_dec',3,'p_cond_dec','lexer_and_parser.py',286),
  ('cond_dec -> INT COLON INIT','cond_dec',3,'p_cond_dec','lexer_and_parser.py',287),
  ('cond_dec -> INT COLON ID COMMA cond_dec','cond_dec',5,'p_cond_dec','lexer_and_parser.py',288),
  ('cond_dec -> INT COLON INIT COMMA cond_dec','cond_dec',5,'p_cond_dec','lexer_and_parser.py',289),
  ('cond_dec -> nil','cond_dec',1,'p_cond_dec','lexer_and_parser.py',290),
  ('state_dec_wrapper -> ST COLON OPENLIST state_dec CLOSELIST SEMICOLON','state_dec_wrapper',6,'p_state_dec_wrapper','lexer_and_parser.py',297),
  ('state_dec -> INT COLON ID','state_dec',3,'p_state_dec','lexer_and_parser.py',304),
  ('state_dec -> INT COLON INIT','state_dec',3,'p_state_dec','lexer_and_parser.py',305),
  ('state_dec -> INT COLON ID COMMA state_dec','state_dec',5,'p_state_dec','lexer_and_parser.py',306),
  ('state_dec -> INT COLON INIT COMMA state_dec','state_dec',5,'p_state_dec','lexer_and_parser.py',307),
  ('state_dec -> nil','state_dec',1,'p_state_dec','lexer_and_parser.py',308),
  ('trel -> event boolexp ARROW INT SEMICOLON trel','trel',6,'p_trel','lexer_and_parser.py',315),
  ('trel -> nil','trel',1,'p_trel','lexer_and_parser.py',316),
  ('event -> OPENLIST CLOSELIST','event',2,'p_event','lexer_and_parser.py',329),
  ('event -> OPENLIST ID CLOSELIST','event',3,'p_event','lexer_and_parser.py',330),
  ('boolexp -> INT AND GUARD EQUAL ID','boolexp',5,'p_boolexp_wrapper','lexer_and_parser.py',337),
  ('boolexp -> INT AND GUARD EQUAL INT','boolexp',5,'p_boolexp_wrapper','lexer_and_parser.py',338),
  ('boolexp -> INT','boolexp',1,'p_boolexp_wrapper','lexer_and_parser.py',339),
]
